version: "3.7"

services:
  neptun-service:
    build: ./
    container_name: neptun-service
    restart: always
    ports:
      - "7700:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/logs:/usr/src/app/logs
      - /opt/telegram:/volume1/bin/telegram:ro
    command:
      "node ./index.js"
